name: ut and tarballs

on:
  push:
    branches-ignore: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  ut:
    uses: salesforcecli/github-workflows/.github/workflows/unitTest.yml@main
  tarballs:
    uses: salesforcecli/github-workflows/.github/workflows/tarballs.yml@main
